import './globals.css';
import Navbar from '@/components/layout/Navbar';
import 'swiper/css';
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" dir='rtl'>
      <body className="font-vazir">
      <Navbar />
      {children}
      </body>
    </html>
  )
}
